function AiryCrust = airyEqualPressures(topography, crustDensity, ...
    mantleDensity, referenceDepth, g0, crustGravity)
    extraDepth = topography * crustDensity / ...
        (mantleDensity - crustDensity) *  (g0 / crustGravity);
    AiryCrust = referenceDepth + topography + extraDepth;
end
